import type { User } from "./user-types";

export const USERS: User[] = [
    {
        id: "1",
        name: "Florence Shaw",
        email: "florence@untitledui.com",
        role: "Owner",
        permissions: ["Admin", "Data Export", "Data Import"],
        lastActive: "Mar 4, 2024",
        dateAdded: "Jul 4, 2022",
        status: "Active",
    },
    {
        id: "2",
        name: "Amélie Laurent",
        email: "amelie@untitledui.com",
        role: "Admin",
        permissions: ["Data Export", "Data Import"],
        lastActive: "Mar 4, 2024",
        dateAdded: "Jul 4, 2022",
        status: "Active",
    },
    {
        id: "3",
        name: "Ammar Foley",
        email: "ammar@untitledui.com",
        role: "Member",
        permissions: ["Data Export", "Data Import"],
        lastActive: "Mar 2, 2024",
        dateAdded: "Jul 4, 2022",
        status: "Invited",
    },
    {
        id: "4",
        name: "Caitlyn King",
        email: "caitlyn@untitledui.com",
        role: "Member",
        permissions: ["Data Export"],
        lastActive: "Mar 6, 2024",
        dateAdded: "Jul 4, 2022",
        status: "Active",
    },
    {
        id: "5",
        name: "Sienna Hewitt",
        email: "sienna@untitledui.com",
        role: "Admin",
        permissions: ["Data Export", "Data Import"],
        lastActive: "Mar 8, 2024",
        dateAdded: "Jul 4, 2022",
        status: "Suspended",
    },
];
