import type {Ticket} from "./ticket-types.ts";
export const TICKETS: Ticket[] = [
    {
        id: "001",
        title: "User cannot receive notifications",
        platform: "Indy",
        category: "Bug",
        priority: "High",
        team: "Frontend",
        assignee: "Jane Doe",
        submittedBy: "Jane Doe",
        date: "25 Jun 2025",
        status: "In Progress",
    },
    {
        id: "002",
        title: "Improve ticket search performance",
        platform: "MCC",
        category: "Suggestion",
        priority: "Medium",
        team: "Backend",
        assignee: "John Doe",
        submittedBy: "Jane Doe",
        date: "25 Jun 2025",
        status: "Done",
    },
    {
        id: "003",
        title: "UI glitch on mobile ticket view",
        platform: "ILG",
        category: "Bug",
        priority: "Low",
        team: "Frontend",
        assignee: "Jane Doe",
        submittedBy: "John Doe",
        date: "24 Jun 2025",
        status: "For Release",
    },
    {
        id: "004",
        title: "Add bulk export feature",
        platform: "Zambero",
        category: "Suggestion",
        priority: "Low",
        team: "Backend",
        assignee: "Jane Doe",
        submittedBy: "Jane Doe",
        date: "24 Jun 2025",
        status: "For Testing",
    },
    {
        id: "005",
        title: "Notification email duplicated",
        platform: "Indy",
        category: "Bug",
        priority: "High",
        team: "Frontend",
        assignee: "John Doe",
        submittedBy: "Jane Doe",
        date: "23 Jun 2025",
        status: "Returned",
    },
    {
        id: "006",
        title: "Add custom ticket fields",
        platform: "MCC",
        category: "Suggestion",
        priority: "Medium",
        team: "Backend",
        assignee: "Jane Doe",
        submittedBy: "John Doe",
        date: "22 Jun 2025",
        status: "To Do",
    },
];
